### ISSUE TITLE
demo下载后启动项目报以下错误，是因为什么呢？

### ISSUE THREAD

**Issue by xiaotang66** [framework7io/framework7-template-webpack#7]
TypeError: 'undefined' is not a function (evaluating 'Array.from({
    length: 12
  })')
Viewport argument key "minimal-ui" not recognized and ignored.
Viewport argument key "viewport-fit" not recognized and ignored.

**Comment by nolimits4web** [comment]
Update Framework7 to latest version or use Framework7 CLI instead
